// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconHeroiconsOutline:userCircle': typeof import('~icons/heroicons-outline/user-circle')['default']
    'IconHeroiconsSolid:logout': typeof import('~icons/heroicons-solid/logout')['default']
    'IconLineMd:menu': typeof import('~icons/line-md/menu')['default']
    'IconMajesticons:cloudLine': typeof import('~icons/majesticons/cloud-line')['default']
    'IconMajesticons:dashboardLine': typeof import('~icons/majesticons/dashboard-line')['default']
    'IconMajesticons:locationMarkerLine': typeof import('~icons/majesticons/location-marker-line')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
