// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconGg:creditCard': typeof import('~icons/gg/credit-card')['default']
    'IconGg:profile': typeof import('~icons/gg/profile')['default']
    'IconGg:wallet': typeof import('~icons/gg/wallet')['default']
    'IconHeroiconsOutline:currencyDollar': typeof import('~icons/heroicons-outline/currency-dollar')['default']
    'IconHeroiconsOutline:dotsVertical': typeof import('~icons/heroicons-outline/dots-vertical')['default']
    'IconHeroiconsOutline:fire': typeof import('~icons/heroicons-outline/fire')['default']
    'IconHeroiconsSolid:logout': typeof import('~icons/heroicons-solid/logout')['default']
    'IconTabler:wallet': typeof import('~icons/tabler/wallet')['default']
    'IconUil:moneyInsert': typeof import('~icons/uil/money-insert')['default']
    'IconUil:moneyWithdraw': typeof import('~icons/uil/money-withdraw')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
